repositories:
- name: "incubator"
  url: "https://kubernetes-charts-incubator.storage.googleapis.com"

releases:

################################################################################
## Kubernetes Raw Charts #######################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/incubator/raw
#

- name: "raw-cluster-role-bindings"
  namespace: "common"
  labels:
    chart: "raw"
    repo: "incubator"
    component: "cluster-role-bindings"
    namespace: "common"
    vendor: "kubernetes"
    default: "true"
  chart: "incubator/raw"
  version: "0.1.0"
  wait: true
  installed: true
  values:
  - resources:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: oidc-cluster-admin
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: Group
        name: kubernetes-admins
