repositories:
- name: incubator
  url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:

################################################################################
## Kubernetes Raw Charts #######################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/incubator/raw
#

- name: raw-rook-ceph
  namespace: common
  labels:
    chart: raw
    repo: incubator
    component: rook-ceph
    namespace: common
    vendor: kubernetes
    default: true
  chart: incubator/raw
  version: 0.1.0
  wait: true
  installed: true
  values:
  - resources:

    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      metadata:
        name: rook-ceph
        namespace: common
      spec:
        cephVersion:
          ## For the latest ceph images, see https://hub.docker.com/r/ceph/ceph/tags
          ## Stay on v13.x until Rook Ceph supports v14.x
          image: ceph/ceph:v13.2.5-20190410
        dataDirHostPath: /opt/ceph/disk1
        network:
          hostNetwork: false
        dashboard:
          enabled: true
        mon:
          count: 3
          allowMultiplePerNode: false
        storage:
          useAllNodes: true
          config:
            databaseSizeMB: "1024"
            journalSizeMB: "1024"
      
    - apiVersion: ceph.rook.io/v1
      kind: CephBlockPool
      metadata:
        name: replicapool
        namespace: common
      spec:
        failureDomain: host
        replicated:
          size: 3

    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
         name: rook-ceph-block
      provisioner: ceph.rook.io/block
      parameters:
        blockPool: replicapool
        # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
        clusterNamespace: common
        # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
        fstype: ext4
      # Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
      reclaimPolicy: Retain
